version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "8070:8070"
    volumes:
     - db:/var/lib/postgresql/data
volumes:
  db: 